### ISSUE TITLE
Audit OC 204

### ISSUE THREAD

**Issue by jkamins7** [HopkinsIDD/cholera-database#335] opened 2019-04-10 16:40 UTC

**Comment by eclee25** [comment] 2019-06-19 00:00
OC 204 is a duplicate of OC 209 #339 (same source document with same data input). I already audited OC 209, so I am marking this one for deletion.

**Comment by eclee25** [comment] 2019-07-06 19:54
Checked duplication and deleted OC.

**Closed by eclee25** 2019-07-06 19:54 UTC
Labels: Deletion, Needs Audit
