### ISSUE TITLE
OC 20400

### ISSUE THREAD

**Issue by mayademby** [HopkinsIDD/cholera-database#493] opened 2019-06-17 19:10 UTC
https://www.who.int/csr/don/archive/disease/cholera/en/
(Cholera in Mexico, 19 Oct 2013)

- Should I have included gender as a custom observation field?

**Comment by eclee25** [comment] 2019-06-18 17:52
Yep - the age and sex strata look good, but those three observations should also be marked as cCh since the article describes them all as confirmed cases.

**Closed** 2019-06-21 16:21 UTC
Labels: New Entry
